name: Update Weather Data

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute (GitHub does not support intervals shorter than 1 minute)
  workflow_dispatch:  # To manually trigger the action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch weather data
      run: |
        curl -s "https://api.weatherapi.com/v1/current.json?key=106588a0a19a4cbe91c62044241111&q=Palanpur&aqi=no" -o weather_data.json

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token from GitHub Secrets
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "dev.taiyab@gmail.com"
        git add weather_data.json
        git commit -m "Updated weather data"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/TaiyabMachhaliy/JSON.git

