name: Update Weather Data

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute (since GitHub doesn't support intervals shorter than 1 minute)
  workflow_dispatch:  # To manually trigger the action


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch weather data
      run: |
        curl -s "https://api.weatherapi.com/v1/current.json?key=106588a0a19a4cbe91c62044241111&q=Palanpur&aqi=no" -o weather_data.json

    - name: Update JSON file in repository
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "GitHub Actions"
        author_email: "dev.taiyab@gmail.com"
        message: "Updated weather data"
        add: "weather_data.json"
